### ISSUE TITLE
useNativeDriver breaks functionality

### ISSUE THREAD

**Issue by simonasdev** [bartgryszko/react-native-circular-progress#228]
Since `useNativeDriver: true` is now in `defaultProps`, this https://github.com/facebook/react-native/issues/16218 has started to occur by default. Using `useNativeDriver={false}` works as expected. 
Probably a bug in react-native's `Animated` API, but they've closed that issue even though it was not fixed. Unless there is a way to work around this, I'd suggest removing `useNativeDriver` from `defaultProps`.
Maybe someone got it to work with the latest version?

**Comment by aboveyunhai** [comment]
It seems like a bug in RN library based on multiple issue posts. Unless you recreate the component, `fill` or 'other issue props' will remain `undefined`. 
The merge #227 is intend to get rid of the new RN warning so the current fix is set `useNativeDriver={false}` in `defaultProps` so the warning would not appear or simply revert the pull.

**Comment by markusl** [comment]
I believe this is now fixed in 1.3.6 by #234

**Comment by mandelmonkey** [comment]
this error still happens for me, in 1.3.6 I get The prop fill is marked as required but is undefined
on android running in the device

**Comment by flikQ** [comment]
I am also getting this issue on both ios and Android on 1.3.6

**Comment by danielfx90** [comment]
Me too, still happening with 1.3.6:
```
"react": "16.13.1",
"react-native": "0.63.2",
"react-native-reanimated": "1.13.0",
"react-native-svg": "12.1.0",
```

**Comment by danielfx90** [comment]
Oh that might be the issue. I am trying to use useNativeDriver with all animations to lighten the JS thread.

Good to know.

**Comment by aboveyunhai** [comment]
> Oh that might be the issue. I am trying to use useNativeDriver with all animations to lighten the JS thread.
> 
> Good to know.

Not only for this package, there are a lot of cases where `useNativeDriver: true` will crush your app especially playing around with `react-native-svg`.  This option is not well supported AFAIK. You might be aware of that.

**Comment by williamgoodhew** [comment]
I am still getting this issue on Android using

"react-native": "0.62.2",
"react": "16.11.0",
"react-native-circular-progress": "^1.3.6",
